### ISSUE TITLE
Update your extensions on GitHub

### ISSUE THREAD

**Issue by Galixte** [cece74/bubblemouse#4]
Hi @cece74,

i’m FRENCH translator for phpBB extensions, i see you have your extensions here: http://www.forum.magazine.edu.gr/forum-phpbb-3-1-x.html.

On Github all your extensions  are not present and for those which are on GitHub: https://github.com/cece74?tab=repositories those are not up to date.

Could you publish all your extension (up to date) on GitHub ? It’s an easiest way to contribute with all of your nice work.

Regards.

**Comment by cece74** [comment]
Hi, no, i no publish in Github. I publish here: http://www.forum.magazine.edu.gr/Thaks !

----Messaggio originale----

Da: notifications@github.com

Data: 22-set-2015 0.34

A: "cece74/bubblemouse"bubblemouse@noreply.github.com

Cc: "cece74"forumacquariofilia@libero.it

Ogg: [bubblemouse] Update your extensions on GitHub (#4)

Hi @cece74,

i’m FRENCH translator for phpBB extensions, i see you have your extensions here: http://www.forum.magazine.edu.gr/forum-phpbb-3-1-x.html.

On Github all your extensions  are not present and for those which are on GitHub: https://github.com/cece74?tab=repositories those are not up to date.

Could you publish all your extension (up to date) on GitHub ? It’s an easiest way to contribute with all of your nice work.

Regards.

**Comment by Galixte** [comment]
Thanks for informations, too bad it is regrettable.
